config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root to: 'friends#index', as: 'root'
  get 'dashboard', to: 'friends#dashboard', as: 'dashboard'  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /dasboard/ or /dasboard.json
  def dashboard
    @friends = Friend.where("user_id = " + current_user.id.to_s )
    @totalFriends = @friends.length
    @totalMingguKemarin = @friends.where(created_at: 1.week.ago.all_week).length
    # @totalMingguKemarin = @friends.where(created_at: (1.hours.ago)..Time.now).length
    @totalMingguIni = @friends.where(created_at: Date.today.all_week).length
    @totalBulanKemarin = @friends.where(created_at: 1.month.ago.all_month).length
    @totalBulanIni = @friends.where(created_at: Date.today.all_month).length
    @totalTahunKemarin = @friends.where(created_at: 1.year.ago.all_year).length
    @totalTahunIni = @friends.where(created_at: Date.today.all_year).length
    def persentaseKenaikan(awal, akhir)
      return awal <= 0 ? 100.to_f : (((akhir - awal).to_f / awal) * 100).to_f
    end
    @persentaseMingguIni = persentaseKenaikan(@totalMingguKemarin, @totalMingguIni)
    @persentaseBulanIni = persentaseKenaikan(@totalBulanKemarin, @totalBulanIni)
    @persentaseTahunIni = persentaseKenaikan(@totalTahunKemarin, @totalTahunIni)
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: I18n.t('friend.create') }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: I18n.t('friend.update') }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: I18n.t('friend.destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:name, :email, :phone, :instagram, :user_id)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<div class="mt-10 sm:mt-0">
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="md:col-span-1">
      <div class="px-4 sm:px-0">
        <h3 class="text-lg font-medium leading-6 text-gray-900">Personal Information</h3>
        <% if friend.errors.any? %>
        <h5 class="mt-1 text-sm text-gray-600"><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h5>

        <ul>
          <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
          <% end %>
        </ul>
        <% end %>
      </div>
    </div>
    <div class="mt-5 md:mt-0 md:col-span-2">
      <%= form_with(model: friend) do |form| %>
      <div class="shadow overflow-hidden sm:rounded-md">
        <div class="px-4 py-5 bg-white sm:p-6">
          <div class="col-span-6 py-2">
            <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
            <%= form.text_field :name, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", autocomplete: "nama" %>
          </div>
          <div class="col-span-6 py-5">
            <%= form.label :email, class: "block text-sm font-medium text-gray-700" %>
            <%= form.text_field :email, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", autocomplete: "email" %>
          </div>
          <div class="col-span-6 py-5">
            <%= form.label :phone, class: "block text-sm font-medium text-gray-700" %>
            <%= form.text_field :phone, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
          </div>
          <div class="col-span-6 py-5">
            <%= form.label :instagram, class: "block text-sm font-medium text-gray-700" %>
            <%= form.text_field :instagram, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
          </div>
          <div class="col-span-6">
            <%= form.number_field :user_id, type: :hidden, id: :friend_user_id, value: current_user.id, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
          </div>
        </div>
        <div class="px-4 py-3 bg-gray-50 flex justify-between sm:px-6">
          <%# form.submit %>
          <a href="<%= root_path %>" class="hover:bg-transparent">
            <button type="button" class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-gray-500 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
              Back
            </button>
          </a>
          <button type="submit" name="commit" value="Create Friend" data-disable-with="Create Friend" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Save
          </button>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/friends/edit.html.erb
<% content_for :header do %>
<header class="bg-white shadow">
  <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 flex justify-between lg:px-8">
    <h1 class="text-3xl font-bold leading-tight text-gray-900">
      Edit Friend Information
    </h1>
  </div>
</header>
<% end %>

<% content_for :content do %>
<%= render 'form', friend: @friend %>
<% end %>

app/views/friends/index.html.erb
<% content_for :header do %>
<header class="bg-white shadow">
  <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 flex justify-between lg:px-8">
    <h1 class="text-3xl font-bold leading-tight text-gray-900">
      <% if @friends.length < 1 %>
      Home
      <% elsif @friends.length == 1 %>
      My Friend
      <% else %>
      My Friends
      <% end %>
    </h1>
    <span class="hidden sm:block">
      <% if @friends.exists? %>
      <a href="<%= new_friend_path %>">
        <button type="button" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <i class="fas fa-user-plus mr-2"></i>
          Add Friend
        </button>
      </a>
      <% end %>
    </span>
  </div>
</header>
<% end %>

<% content_for :content do %>
<% if @friends.exists? %>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-10 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Phone
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Instagram
              </th>
              <th scope="col" class="relative px-6 py-3 tracking-wider">
                Action
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @friends.each do |friend| %>
            <% if friend.user == current_user %>
            <tr>
              <td class="px-10 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <!--
                        <div class="flex-shrink-0 h-10 w-10">
                          <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=60" alt="">
                        </div>
                        -->
                  <!-- Default: ml-4 -->
                  <div>
                    <div class="text-sm font-medium text-gray-900">
                      <%= friend.name %>
                    </div>
                    <div class="text-sm text-gray-500">
                      <%= friend.email %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= friend.phone %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                <%= friend.instagram %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium">
                <a href="/friends/<%= friend.id %>" class="inline-flex justify-center items-center py-2 px-3 mx-1 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  <i class="fas fa-id-badge mr-2"></i> Show
                </a>
                <a href="/friends/<%= friend.id %>" data-method="delete" data-confirm="Are you sure?" rel="nofollow" class="inline-flex justify-center items-center py-2 px-3 mx-1 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                  <i class="fas fa-user-slash mr-2"></i> Delete
                </a>
              </td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
  <h2 class="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl">
    <span class="block">There is no friend.🤷‍♂️</span>
    <span class="block text-indigo-600">Create a new one.</span>
  </h2>
  <div class="mt-8 flex lg:mt-0 lg:flex-shrink-0">
    <div class="inline-flex rounded-md shadow">
      <a href="<%= new_friend_path %>">
        <button type="button" class="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <i class="fas fa-user-plus mr-2"></i>
          Add Friend
        </button>
      </a>
    </div>
  </div>
</div>
<% end %>
<% end %>

app/views/friends/new.html.erb
<% content_for :header do %>
<header class="bg-white shadow">
  <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 flex justify-between lg:px-8">
    <h1 class="text-3xl font-bold leading-tight text-gray-900">
      Create Friend
    </h1>
  </div>
</header>
<% end %>

<% content_for :content do %>
<%= render 'form', friend: @friend %>
<% end %>

app/views/friends/show.html.erb
<% content_for :header do %>
<header class="bg-white shadow">
  <div class="max-w-7xl mx-auto py-6 flex items-center justify-between px-4 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold leading-tight text-gray-900">
      Show Detail Information
    </h1>
    <span class="hidden sm:block">
      <a href="<%= new_friend_path %>">
        <button type="button" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <i class="fas fa-user-plus mr-2"></i>
          Add Friend
        </button>
      </a>
    </span>
  </div>
</header>
<% end %>

<% content_for :content do %>
<div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      <span><%= @friend.name.split(" ")[0, 2].join(" ").capitalize %></span> detail information
    </h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">
      Personal details and privacy.
    </p>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Full name
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @friend.name %>
        </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Email
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @friend.email %>
        </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Phone number
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @friend.phone %>
        </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Instagram
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @friend.instagram %>
        </dd>
      </div>
    </dl>
  </div>
  <div class="w-78 px-4 py-5 flex justify-between items-center">
    <a href="<%= edit_friend_path(@friend) %>" class="hover:bg-transparent">
      <button type="button" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-50">
        <i class="fas fa-user-edit mr-2"></i>
        Edit
      </button>
    </a>
    <div class="w-64 flex items-center justify-between">
      <a href="<%= dashboard_path %>" class="hover:bg-transparent">
        <button type="button" class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
          <i class="fas fa-users mr-2"></i>
          Dashboard
        </button>
      </a>
      <a href="<%= root_path %>" class="hover:bg-transparent">
        <button type="button" class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <i class="fas fa-user-check mr-2"></i>
          Home
        </button>
      </a>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Rails CRUD</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'tailwind', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'fontawesome/css/fontawesome.min.css'%>
  <%= javascript_pack_tag 'rails', 'data-turbolinks-track': 'reload' %>
  <%= yield :head or "" %>
</head>

<body>
  <% if user_signed_in? %>
  <%= render 'components/Navbar' %>
  <%= yield :header or "" %>
  <main class="py-10 px-20">
    <% if notice %>
    <%= render 'components/Notification' %>
    <% end %>
    <%= yield :content or "" %>
  </main>
  <%= javascript_include_tag "application" %>
  <% else %>
  <%= yield or "" %>
  <% end %>
</body>

</html>